#pragma once
#ifndef _FUSIN_MOTION_TRACKER_H
#define _FUSIN_MOTION_TRACKER_H

#include "FusinIOCode.h"
#include "FusinPrerequisites.h"
#include <vector>

namespace Fusin
{
	const IOCode ANY_MOTION_TRACKER_GYRO_YAW = IOCode(DT_ANY_MOTION_TRACKER, IO_GYRO, 0);
	const IOCode ANY_MOTION_TRACKER_GYRO_PITCH = IOCode(DT_ANY_MOTION_TRACKER, IO_GYRO, 1);
	const IOCode ANY_MOTION_TRACKER_GYRO_ROLL = IOCode(DT_ANY_MOTION_TRACKER, IO_GYRO, 2);
	const IOCode ANY_MOTION_TRACKER_ACCELERATION_X = IOCode(DT_ANY_MOTION_TRACKER, IO_ACCELERATION, 0);
	const IOCode ANY_MOTION_TRACKER_ACCELERATION_Y = IOCode(DT_ANY_MOTION_TRACKER, IO_ACCELERATION, 1);
	const IOCode ANY_MOTION_TRACKER_ACCELERATION_Z = IOCode(DT_ANY_MOTION_TRACKER, IO_ACCELERATION, 2);
	const IOCode ANY_MOTION_TRACKER_ORIENTATION_YAW = IOCode(DT_ANY_MOTION_TRACKER, IO_ORIENTATION, 0);
	const IOCode ANY_MOTION_TRACKER_ORIENTATION_PITCH = IOCode(DT_ANY_MOTION_TRACKER, IO_ORIENTATION, 1);
	const IOCode ANY_MOTION_TRACKER_ORIENTATION_ROLL = IOCode(DT_ANY_MOTION_TRACKER, IO_ORIENTATION, 2);
	const IOCode ANY_MOTION_TRACKER_VELOCITY_X = IOCode(DT_ANY_MOTION_TRACKER, IO_VELOCITY, 0);
	const IOCode ANY_MOTION_TRACKER_VELOCITY_Y = IOCode(DT_ANY_MOTION_TRACKER, IO_VELOCITY, 1);
	const IOCode ANY_MOTION_TRACKER_VELOCITY_Z = IOCode(DT_ANY_MOTION_TRACKER, IO_VELOCITY, 2);
	const IOCode ANY_MOTION_TRACKER_POSITION_X = IOCode(DT_ANY_MOTION_TRACKER, IO_WORLD_POSITION, 0);
	const IOCode ANY_MOTION_TRACKER_POSITION_Y = IOCode(DT_ANY_MOTION_TRACKER, IO_WORLD_POSITION, 1);
	const IOCode ANY_MOTION_TRACKER_POSITION_Z = IOCode(DT_ANY_MOTION_TRACKER, IO_WORLD_POSITION, 2);

	const IOCode ANY_MOTION_TRACKER_GYRO_YAW_NEGATIVE = MOTION_TRACKER_GYRO_YAW.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_GYRO_PITCH_NEGATIVE = MOTION_TRACKER_GYRO_PITCH.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_GYRO_ROLL_NEGATIVE = MOTION_TRACKER_GYRO_ROLL.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_ACCELERATION_X_NEGATIVE = MOTION_TRACKER_ACCELERATION_X.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_ACCELERATION_Y_NEGATIVE = MOTION_TRACKER_ACCELERATION_Y.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_ACCELERATION_Z_NEGATIVE = MOTION_TRACKER_ACCELERATION_Z.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_ORIENTATION_YAW_NEGATIVE = MOTION_TRACKER_ORIENTATION_YAW.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_ORIENTATION_PITCH_NEGATIVE = MOTION_TRACKER_ORIENTATION_PITCH.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_ORIENTATION_ROLL_NEGATIVE = MOTION_TRACKER_ORIENTATION_ROLL.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_VELOCITY_X_NEGATIVE = MOTION_TRACKER_VELOCITY_X.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_VELOCITY_Y_NEGATIVE = MOTION_TRACKER_VELOCITY_Y.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_VELOCITY_Z_NEGATIVE = MOTION_TRACKER_VELOCITY_Z.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_POSITION_X_NEGATIVE = MOTION_TRACKER_POSITION_X.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_POSITION_Y_NEGATIVE = MOTION_TRACKER_POSITION_Y.negativeVersion();
	const IOCode ANY_MOTION_TRACKER_POSITION_Z_NEGATIVE = MOTION_TRACKER_POSITION_Z.negativeVersion();

	const IOCode ANY_MOTION_TRACKER_GYRO_YAW_POSITIVE = MOTION_TRACKER_GYRO_YAW.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_GYRO_PITCH_POSITIVE = MOTION_TRACKER_GYRO_PITCH.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_GYRO_ROLL_POSITIVE = MOTION_TRACKER_GYRO_ROLL.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_ACCELERATION_X_POSITIVE = MOTION_TRACKER_ACCELERATION_X.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_ACCELERATION_Y_POSITIVE = MOTION_TRACKER_ACCELERATION_Y.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_ACCELERATION_Z_POSITIVE = MOTION_TRACKER_ACCELERATION_Z.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_ORIENTATION_YAW_POSITIVE = MOTION_TRACKER_ORIENTATION_YAW.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_ORIENTATION_PITCH_POSITIVE = MOTION_TRACKER_ORIENTATION_PITCH.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_ORIENTATION_ROLL_POSITIVE = MOTION_TRACKER_ORIENTATION_ROLL.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_VELOCITY_X_POSITIVE = MOTION_TRACKER_VELOCITY_X.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_VELOCITY_Y_POSITIVE = MOTION_TRACKER_VELOCITY_Y.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_VELOCITY_Z_POSITIVE = MOTION_TRACKER_VELOCITY_Z.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_POSITION_X_POSITIVE = MOTION_TRACKER_POSITION_X.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_POSITION_Y_POSITIVE = MOTION_TRACKER_POSITION_Y.positiveVersion();
	const IOCode ANY_MOTION_TRACKER_POSITION_Z_POSITIVE = MOTION_TRACKER_POSITION_Z.positiveVersion();

	const const std::vector<String> POSITION_NAMES = {
		FUSIN_STR("X"), FUSIN_STR("Y"), FUSIN_STR("Z")
	};
	const const std::vector<String> ROTATION_NAMES = {
		FUSIN_STR("Yaw"), FUSIN_STR("Pitch"), FUSIN_STR("Roll")
	};

	const const std::vector<String> MOTION_TRACKER_GYRO_NAMES = {
		FUSIN_STR("Gyro_Yaw"), FUSIN_STR("Gyro_Pitch"), FUSIN_STR("Gyro_Roll")
	};
	const const std::vector<String> MOTION_TRACKER_ACCELERATION_NAMES = {
		FUSIN_STR("Accel_X"), FUSIN_STR("Accel_Y"), FUSIN_STR("Accel_Z")
	};
	const const std::vector<String> MOTION_TRACKER_ORIENTATION_NAMES = {
		FUSIN_STR("Orientation_Yaw"), FUSIN_STR("Orientation_Pitch"), FUSIN_STR("Orientation_Roll")
	};
	const const std::vector<String> MOTION_TRACKER_VELOCITY_NAMES = {
		FUSIN_STR("Velocity_X"), FUSIN_STR("Velocity_Y"), FUSIN_STR("Velocity_Z")
	};
	const const std::vector<String> MOTION_TRACKER_POSITION_NAMES = {
		FUSIN_STR("WPosition_X"), FUSIN_STR("WPosition_Y"), FUSIN_STR("WPosition_Z")
	};

}

#endif